feat: guild routes
pycord/pycord-v3 pull request #15
Opened 2022-07-14 17:59 UTC by plun1331

Everything under https://discord.com/developers/docs/resources/guild

~~I couldn't find some things in `discord_typings` so I left them as `dict` to be fixed later.~~ Added in `pycord/types.py`

~~Unsure of the return type for `modify_guild_mfa_level`~~ `{"level": 0}`

Also moves `Route` to its own file to avoid circular imports, and adds kwargs to the `request` method

2022-07-14 18:15 UTC, Middledot commented on pycord/internal/http/guild.py
> +    # TODO: use something other than ellipsis
Maybe a blank `MISSING` class?

2022-07-14 18:19 UTC, Middledot commented on pycord/internal/http/guild.py
> +    request: Callable[..., Coroutine[Any, Any, dict[str, Any] | list[dict[str, Any]] | str]]
```python
    _session: ClientSession
    request: Callable[..., Coroutine[Any, Any, dict[str, Any] | list[dict[str, Any]] | str]]
```
A mixin for these route classes with common types could be useful

2022-07-14 18:31 UTC, plun1331 commented on pycord/internal/http/guild.py
> +    # TODO: use something other than ellipsis
Would be helpful yes

2022-07-14 18:52 UTC, Middledot commented on pycord/internal/http/guild.py
> +    request: Callable[..., Coroutine[Any, Any, dict[str, Any] | list[dict[str, Any]] | str]]
Since it's the first to implement (class) routes it's probably in-scope

2022-07-14 18:59 UTC, plun1331 commented on pycord/internal/http/guild.py
> +    request: Callable[..., Coroutine[Any, Any, dict[str, Any] | list[dict[str, Any]] | str]]
would it go in `pycord/mixins`?

2022-07-14 19:04 UTC, Middledot commented on pycord/internal/http/guild.py
> +    request: Callable[..., Coroutine[Any, Any, dict[str, Any] | list[dict[str, Any]] | str]]
Yeah it could go there

2022-07-14 19:16 UTC, plun1331 commented
just tested, works as expected

2022-07-14 19:18 UTC, Middledot commented on pycord/internal/http/guild.py
> +        return await self.request("PATCH", Route("/guilds/{guild_id}/mfa", guild_id=guild_id), payload)
This exists?

2022-07-14 19:19 UTC, plun1331 commented on pycord/internal/http/guild.py
> +        return await self.request("PATCH", Route("/guilds/{guild_id}/mfa", guild_id=guild_id), payload)
It's documented although the return type is a little vague

2022-07-14 19:48 UTC, Middledot commented on pycord/internal/http/guild.py
> +        return await self.request("PATCH", Route("/guilds/{guild_id}/mfa", guild_id=guild_id), payload)
Oh, I was looking at the canary docs. 

And when I tested it, it seems to work:
![image](https://user-images.githubusercontent.com/78228142/179070079-e590cbaf-6348-4061-82c9-0dd5b2a7816d.png)

2022-07-14 19:49 UTC, plun1331 commented on pycord/internal/http/guild.py
> +        return await self.request("PATCH", Route("/guilds/{guild_id}/mfa", guild_id=guild_id), payload)
I must have misread the docs, it was passing `mfa_level` as opposed to `level`

2022-07-14 19:53 UTC, Middledot approved these changes

2022-07-14 19:59 UTC, EmreTech requested changes

2022-07-14 19:59 UTC, EmreTech commented on pycord/internal/http/__init__.py
> +                **kwargs,
If there are kwargs instead of the data attribute being set, shouldn't they be treated like a dict?

2022-07-14 19:59 UTC, EmreTech commented on pycord/internal/http/guild.py
> +from discord_typings import BanData, ChannelData, ChannelPositionData, GuildData, GuildMemberData, GuildPreviewData, \
Unnecessary, what you can do instead is something like this:
```python
from cool_module import (
    thing1,
    thing2,
    thing3,
    thing4,
    thing5,
    thing6,
    thing7,
)
```

2022-07-14 19:59 UTC, EmreTech commented on pycord/internal/http/guild.py
> +from .route import Route
Why does this one use a relative import but the rest don't?

2022-07-14 19:59 UTC, EmreTech commented on pycord/internal/http/guild.py
> +            name: str,
I feel like this parameter should also be keywords only

2022-07-14 19:59 UTC, EmreTech commented on pycord/internal/http/guild.py
> +            premium_progress_bar_enabled: bool = MISSING,
You should use union types on all of these parameters and any other ones that are set to `None` or `MISSING` by default. That might make static type checkers a little happier.

2022-07-14 19:59 UTC, EmreTech commented on pycord/internal/http/guild.py
> +    async def create_guild_channel(
This might be more appropriate in a channel route section, but that's just me

2022-07-14 19:59 UTC, EmreTech commented on pycord/internal/http/route.py
> +from discord_typings import Snowflake
Docstring

2022-07-14 19:59 UTC, EmreTech commented on pycord/utils.py
> +        return "..."
To confuse less people, this should return `MISSING` instead of `...`
This is taken directly from discord.py and I'm really not a fan of it.

2022-07-14 20:06 UTC, plun1331 commented on pycord/internal/http/guild.py
> +    async def create_guild_channel(
I just did them how they were documented

2022-07-14 20:08 UTC, plun1331 commented on pycord/internal/http/__init__.py
> +                **kwargs,
Unsure what you mean by this

2022-07-14 20:16 UTC, EmreTech commented on pycord/internal/http/__init__.py
> +                **kwargs,
Actually nevermind, I misread the example

2022-07-14 20:18 UTC, EmreTech commented on pycord/internal/http/guild.py
> +            premium_progress_bar_enabled: bool = MISSING,
If the parameter is optional but not nullable (according to the Discord API docs) then add in `MISSING` as a union
If the parameter is nullable but not optional then add in `None` as a union
If the parameter is both optional and nullable, then you can mix in both `None` and `MISSING` as a union

2022-07-14 21:59 UTC, plun1331 commented
I think i did the typehinting right

2022-07-14 22:27 UTC, EmreTech approved these changes

2022-07-15 01:38 UTC, EmreTech approved these changes

2022-07-15 02:35 UTC, EmreTech approved these changes
I'm gonna merge this before you make me review again

2022-07-15 02:36 UTC, merged